db:
  image: postgres
  environment:
    POSTGRES_USER: "daredevil"
    POSTGRES_DB: "daredevil"
    POSTGRES_PASSWORD: 
  ports:
    - "5432:5432"
web:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - db
  stdin_open: true
  tty: true
